#!/bin/bash

commit_message="$1"

# search the config file from bottom to top
config_file=".commit-template"
current_dir=$(pwd)
while [ "$current_dir" != "/" ]; do
  if [ -f "$current_dir/$config_file" ]; then
    break
  fi
  current_dir=$(dirname "$current_dir")
done

# load prefixes from config file
if [ -f "$current_dir/$config_file" ]; then
  mapfile -t prefixes <"$current_dir/$config_file"
else
  echo "Config file not found. Using default prefixes."

  prefixes=("feat" "fix" "chore" "docs" "style" "test")
fi

# select via fzf
selected_prefix=$(printf "%s\n" "${prefixes[@]}" | fzf)

# exit if user didn't select any prefix
[[ -z "$selected_prefix" ]] && exit 1

final_commit_message="$selected_prefix: $commit_message"

echo "Final commit message: $final_commit_message"

git commit -m "$final_commit_message"
